import type { Metadata } from 'next'
import './globals.css'
import { pretendard } from '@/constants/fonts'
import { Header } from '@/components/common/Header'
import { Footer } from '@/components/common/Footer'
import ModalWrapper from '@/components/modal/ModalWrapper'
import ReactQueryProviders from '@/utils/react-query-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        <Header />
        <ReactQueryProviders>
          <ModalWrapper />
          {children}
        </ReactQueryProviders>
        <Footer />
      </body>
    </html>
  )
}
